"""initial_schema_all_tables

Revision ID: ba2f1e70f480
Revises: 
Create Date: 2026-08-16 03:04:04.678066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'ba2f1e70f480'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_places_category', 'places', ['category'], unique=False)
    op.create_index('idx_places_location', 'places', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_places_status', 'places', ['status'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('weather_snapshots',
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rain_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('wind_speed_kph', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_weather_expires', 'weather_snapshots', ['expires_at'], unique=False)
    op.create_index('idx_weather_location', 'weather_snapshots', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_weather_observed_at', 'weather_snapshots', ['observed_at'], unique=False)
    op.create_table('accessibility_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mobility_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vision_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hearing_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cognitive_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('walking_limit_meters', sa.Integer(), nullable=True),
    sa.Column('avoid_stairs', sa.Boolean(), nullable=False),
    sa.Column('prefer_step_free', sa.Boolean(), nullable=False),
    sa.Column('prefer_rest_stops', sa.Boolean(), nullable=False),
    sa.Column('preferred_route_style', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('accessibility_records',
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_accessibility_expires', 'accessibility_records', ['expires_at'], unique=False)
    op.create_index('idx_accessibility_feature', 'accessibility_records', ['feature'], unique=False)
    op.create_index('idx_accessibility_place', 'accessibility_records', ['place_id'], unique=False)
    op.create_index('idx_accessibility_status', 'accessibility_records', ['status'], unique=False)
    op.create_table('assistance_points',
    sa.Column('place_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('assistance_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('availability_status', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assistance_points_location', 'assistance_points', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_assistance_points_place', 'assistance_points', ['place_id'], unique=False)
    op.create_index('idx_assistance_points_type', 'assistance_points', ['assistance_type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_actor', 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('crowd_observations',
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('crowd_level', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crowd_expires', 'crowd_observations', ['expires_at'], unique=False)
    op.create_index('idx_crowd_observed', 'crowd_observations', ['observed_at'], unique=False)
    op.create_index('idx_crowd_place', 'crowd_observations', ['place_id'], unique=False)
    op.create_table('facilities',
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('facility_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_facilities_location', 'facilities', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_facilities_place', 'facilities', ['place_id'], unique=False)
    op.create_index('idx_facilities_type', 'facilities', ['facility_type'], unique=False)
    op.create_table('itineraries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_by', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_itineraries_status', 'itineraries', ['status'], unique=False)
    op.create_index('idx_itineraries_user', 'itineraries', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_location', 'reports', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_reports_place', 'reports', ['place_id'], unique=False)
    op.create_index('idx_reports_status', 'reports', ['status'], unique=False)
    op.create_index('idx_reports_type', 'reports', ['report_type'], unique=False)
    op.create_index('idx_reports_user', 'reports', ['user_id'], unique=False)
    op.create_table('barriers',
    sa.Column('place_id', sa.UUID(), nullable=True),
    sa.Column('reported_by', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('barrier_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_barriers_expires', 'barriers', ['expires_at'], unique=False)
    op.create_index('idx_barriers_location', 'barriers', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_barriers_place', 'barriers', ['place_id'], unique=False)
    op.create_index('idx_barriers_reported_by', 'barriers', ['reported_by'], unique=False)
    op.create_index('idx_barriers_status', 'barriers', ['status'], unique=False)
    op.create_table('itinerary_stops',
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('accessibility_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_itinerary_stops_itinerary', 'itinerary_stops', ['itinerary_id'], unique=False)
    op.create_index('idx_itinerary_stops_place', 'itinerary_stops', ['place_id'], unique=False)
    op.create_table('route_requests',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('origin', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('destination', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['accessibility_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_route_requests_at', 'route_requests', ['requested_at'], unique=False)
    op.create_index('idx_route_requests_destination', 'route_requests', ['destination'], unique=False, postgresql_using='gist')
    op.create_index('idx_route_requests_origin', 'route_requests', ['origin'], unique=False, postgresql_using='gist')
    op.create_index('idx_route_requests_user', 'route_requests', ['user_id'], unique=False)
    op.create_table('evidence',
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('barrier_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['barrier_id'], ['barriers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evidence_barrier', 'evidence', ['barrier_id'], unique=False)
    op.create_index('idx_evidence_report', 'evidence', ['report_id'], unique=False)
    op.create_index('idx_evidence_uploader', 'evidence', ['uploaded_by'], unique=False)
    op.create_table('route_constraints',
    sa.Column('route_request_id', sa.UUID(), nullable=False),
    sa.Column('constraint_type', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['route_request_id'], ['route_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_route_constraints_request', 'route_constraints', ['route_request_id'], unique=False)
    op.create_table('routes',
    sa.Column('route_request_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_route_id', sa.String(length=255), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('distance_meters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('accessibility_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('walking_distance_meters', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stairs_count', sa.Integer(), nullable=True),
    sa.Column('barrier_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('ranking_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['route_request_id'], ['route_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_routes_geometry', 'routes', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('idx_routes_request', 'routes', ['route_request_id'], unique=False)
    op.create_index('idx_routes_score', 'routes', ['accessibility_score'], unique=False)
    op.create_table('verifications',
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('barrier_id', sa.UUID(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['barrier_id'], ['barriers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_verifications_barrier', 'verifications', ['barrier_id'], unique=False)
    op.create_index('idx_verifications_report', 'verifications', ['report_id'], unique=False)
    op.create_index('idx_verifications_verifier', 'verifications', ['verified_by'], unique=False)
    op.create_table('evidence_observations',
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('observation_type', sa.String(length=100), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evidence_obs_evidence', 'evidence_observations', ['evidence_id'], unique=False)
    op.create_table('route_segments',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('distance_meters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('surface_type', sa.String(length=50), nullable=True),
    sa.Column('stairs_count', sa.Integer(), nullable=True),
    sa.Column('accessibility_status', sa.String(length=50), nullable=False),
    sa.Column('barrier_count', sa.Integer(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_route_segments_geometry', 'route_segments', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('idx_route_segments_route', 'route_segments', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_route_segments_route', table_name='route_segments')
    op.drop_index('idx_route_segments_geometry', table_name='route_segments', postgresql_using='gist')
    op.drop_table('route_segments')
    op.drop_index('idx_evidence_obs_evidence', table_name='evidence_observations')
    op.drop_table('evidence_observations')
    op.drop_index('idx_verifications_verifier', table_name='verifications')
    op.drop_index('idx_verifications_report', table_name='verifications')
    op.drop_index('idx_verifications_barrier', table_name='verifications')
    op.drop_table('verifications')
    op.drop_index('idx_routes_score', table_name='routes')
    op.drop_index('idx_routes_request', table_name='routes')
    op.drop_index('idx_routes_geometry', table_name='routes', postgresql_using='gist')
    op.drop_table('routes')
    op.drop_index('idx_route_constraints_request', table_name='route_constraints')
    op.drop_table('route_constraints')
    op.drop_index('idx_evidence_uploader', table_name='evidence')
    op.drop_index('idx_evidence_report', table_name='evidence')
    op.drop_index('idx_evidence_barrier', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('idx_route_requests_user', table_name='route_requests')
    op.drop_index('idx_route_requests_origin', table_name='route_requests', postgresql_using='gist')
    op.drop_index('idx_route_requests_destination', table_name='route_requests', postgresql_using='gist')
    op.drop_index('idx_route_requests_at', table_name='route_requests')
    op.drop_table('route_requests')
    op.drop_index('idx_itinerary_stops_place', table_name='itinerary_stops')
    op.drop_index('idx_itinerary_stops_itinerary', table_name='itinerary_stops')
    op.drop_table('itinerary_stops')
    op.drop_index('idx_barriers_status', table_name='barriers')
    op.drop_index('idx_barriers_reported_by', table_name='barriers')
    op.drop_index('idx_barriers_place', table_name='barriers')
    op.drop_index('idx_barriers_location', table_name='barriers', postgresql_using='gist')
    op.drop_index('idx_barriers_expires', table_name='barriers')
    op.drop_table('barriers')
    op.drop_index('idx_reports_user', table_name='reports')
    op.drop_index('idx_reports_type', table_name='reports')
    op.drop_index('idx_reports_status', table_name='reports')
    op.drop_index('idx_reports_place', table_name='reports')
    op.drop_index('idx_reports_location', table_name='reports', postgresql_using='gist')
    op.drop_table('reports')
    op.drop_index('idx_itineraries_user', table_name='itineraries')
    op.drop_index('idx_itineraries_status', table_name='itineraries')
    op.drop_table('itineraries')
    op.drop_index('idx_facilities_type', table_name='facilities')
    op.drop_index('idx_facilities_place', table_name='facilities')
    op.drop_index('idx_facilities_location', table_name='facilities', postgresql_using='gist')
    op.drop_table('facilities')
    op.drop_index('idx_crowd_place', table_name='crowd_observations')
    op.drop_index('idx_crowd_observed', table_name='crowd_observations')
    op.drop_index('idx_crowd_expires', table_name='crowd_observations')
    op.drop_table('crowd_observations')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_index('idx_audit_created', table_name='audit_logs')
    op.drop_index('idx_audit_actor', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_assistance_points_type', table_name='assistance_points')
    op.drop_index('idx_assistance_points_place', table_name='assistance_points')
    op.drop_index('idx_assistance_points_location', table_name='assistance_points', postgresql_using='gist')
    op.drop_table('assistance_points')
    op.drop_index('idx_accessibility_status', table_name='accessibility_records')
    op.drop_index('idx_accessibility_place', table_name='accessibility_records')
    op.drop_index('idx_accessibility_feature', table_name='accessibility_records')
    op.drop_index('idx_accessibility_expires', table_name='accessibility_records')
    op.drop_table('accessibility_records')
    op.drop_table('accessibility_profiles')
    op.drop_index('idx_weather_observed_at', table_name='weather_snapshots')
    op.drop_index('idx_weather_location', table_name='weather_snapshots', postgresql_using='gist')
    op.drop_index('idx_weather_expires', table_name='weather_snapshots')
    op.drop_table('weather_snapshots')
    op.drop_table('users')
    op.drop_index('idx_places_status', table_name='places')
    op.drop_index('idx_places_location', table_name='places', postgresql_using='gist')
    op.drop_index('idx_places_category', table_name='places')
    op.drop_table('places')
    # ### end Alembic commands ###
